<?php

namespace App\Services\FIRS;

use App\Models\Invoice;

/**
 * Builds UBL 2.1 JSON payloads for FIRS e-Invoicing submission.
 *
 * FIRS accepts BIS Billing 3.0 / PEPPOL-compatible UBL 2.1 in JSON form.
 * Invoice type codes follow UN/CEFACT:
 *   380 = Tax Invoice (B2B)
 *   388 = Simplified Tax Invoice (B2C)
 */
class UblPayloadBuilder
{
    /**
     * Build the full UBL 2.1 JSON payload for a given invoice.
     *
     * @param  Invoice  $invoice  Must have tenant, customer, and items loaded.
     * @param  string   $irn      Invoice Reference Number (generated by IrnService).
     * @return array              Ready to send to FirsApiClient.
     */
    public function build(Invoice $invoice, string $irn): array
    {
        $invoice->loadMissing(['tenant', 'customer', 'items']);

        $typeCode = $invoice->is_b2c ? '388' : '380';

        return [
            // ── Context ───────────────────────────────────────────────────────
            'invoice_id'         => $invoice->id,
            'CustomizationID'    => 'urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0',
            'ProfileID'          => 'urn:fdc:peppol.eu:2017:poacc:billing:01:1.0',

            // ── Invoice header ────────────────────────────────────────────────
            'ID'                 => $invoice->invoice_number,
            'IRN'                => $irn,
            'IssueDate'          => $invoice->invoice_date->format('Y-m-d'),
            'DueDate'            => $invoice->due_date->format('Y-m-d'),
            'InvoiceTypeCode'    => $typeCode,
            'DocumentCurrencyCode' => strtoupper($invoice->currency ?? 'NGN'),
            'Note'               => $invoice->notes,

            // ── Seller (AccountingSupplierParty) ─────────────────────────────
            'AccountingSupplierParty' => $this->buildSupplier($invoice),

            // ── Buyer (AccountingCustomerParty) ──────────────────────────────
            'AccountingCustomerParty' => $this->buildBuyer($invoice),

            // ── Tax total ─────────────────────────────────────────────────────
            'TaxTotal' => [
                [
                    'TaxAmount'         => (float) $invoice->vat_amount,
                    'TaxCurrencyCode'   => 'NGN',
                    'TaxSubtotal'       => [
                        [
                            'TaxableAmount' => (float) $invoice->subtotal,
                            'TaxAmount'     => (float) $invoice->vat_amount,
                            'TaxCategory'   => [
                                'ID'           => 'S',
                                'Percent'      => 7.5,
                                'TaxScheme'    => ['ID' => 'VAT'],
                            ],
                        ],
                    ],
                ],
            ],

            // ── Monetary totals ───────────────────────────────────────────────
            'LegalMonetaryTotal' => [
                'LineExtensionAmount'  => (float) $invoice->subtotal,
                'TaxExclusiveAmount'   => (float) $invoice->subtotal,
                'TaxInclusiveAmount'   => (float) ($invoice->subtotal + $invoice->vat_amount),
                'AllowanceTotalAmount' => (float) $invoice->discount_amount,
                'PayableAmount'        => (float) $invoice->total_amount,
            ],

            // ── Line items ────────────────────────────────────────────────────
            'InvoiceLine' => $this->buildLines($invoice),
        ];
    }

    // ── Private builders ─────────────────────────────────────────────────────

    private function buildSupplier(Invoice $invoice): array
    {
        $tenant = $invoice->tenant;

        return [
            'Party' => [
                'PartyName'               => [['Name' => $tenant->company_name]],
                'PostalAddress'           => [
                    'StreetName'  => $tenant->address ?? '',
                    'CityName'    => $tenant->city ?? '',
                    'CountryCode' => 'NG',
                ],
                'PartyTaxScheme'          => [
                    [
                        'CompanyID' => $tenant->tax_id ?? '',
                        'TaxScheme' => ['ID' => 'VAT'],
                    ],
                ],
                'PartyLegalEntity'        => [
                    ['RegistrationName' => $tenant->company_name],
                ],
                'Contact'                 => [
                    'ElectronicMail' => $tenant->email ?? '',
                ],
            ],
        ];
    }

    private function buildBuyer(Invoice $invoice): array
    {
        $customer = $invoice->customer;

        return [
            'Party' => [
                'PartyName'        => [['Name' => $customer->name]],
                'PostalAddress'    => [
                    'StreetName'  => $customer->address ?? '',
                    'CityName'    => $customer->city ?? '',
                    'CountryCode' => 'NG',
                ],
                'PartyTaxScheme'   => [
                    [
                        'CompanyID' => $customer->tax_id ?? '',
                        'TaxScheme' => ['ID' => 'VAT'],
                    ],
                ],
                'PartyLegalEntity' => [
                    ['RegistrationName' => $customer->name],
                ],
                'Contact'          => [
                    'ElectronicMail' => $customer->email ?? '',
                ],
            ],
        ];
    }

    private function buildLines(Invoice $invoice): array
    {
        return $invoice->items->map(function ($item, $index) {
            $vatPercent = $item->vat_applicable ? 7.5 : 0.0;
            $taxCode    = $item->vat_applicable ? 'S' : 'Z';

            return [
                'ID'                  => (string) ($index + 1),
                'InvoicedQuantity'    => [
                    'unitCode' => 'EA',
                    'value'    => (float) $item->quantity,
                ],
                'LineExtensionAmount' => (float) $item->subtotal,
                'Item'               => [
                    'Description'     => $item->description,
                    'Name'            => $item->description,
                    'ClassifiedTaxCategory' => [
                        [
                            'ID'        => $taxCode,
                            'Percent'   => $vatPercent,
                            'TaxScheme' => ['ID' => 'VAT'],
                        ],
                    ],
                ],
                'Price'              => [
                    'PriceAmount'              => (float) $item->unit_price,
                    'BaseQuantity'             => 1,
                    'AllowanceCharge'          => [],
                ],
                'TaxTotal'           => [
                    [
                        'TaxAmount'   => (float) $item->vat_amount,
                        'TaxSubtotal' => [
                            [
                                'TaxableAmount' => (float) $item->subtotal,
                                'TaxAmount'     => (float) $item->vat_amount,
                                'TaxCategory'   => [
                                    'ID'        => $taxCode,
                                    'Percent'   => $vatPercent,
                                    'TaxScheme' => ['ID' => 'VAT'],
                                ],
                            ],
                        ],
                    ],
                ],
            ];
        })->values()->all();
    }
}
